const mongoose = require('mongoose');
const inspectionSchema = new mongoose.Schema({
  clientInformation: {
    contactName: { type: String },
    clientAddress: { type: String },
    phoneNumber: { type: String },
    email: { type: String },
  },
  inspectionCompany: {
    inspectorName: { type: String },
    inspectionAddress: { type: String },
    phoneNumber: { type: String },
    email: { type: String },
  },
  buildingForm: {
    estimatedAge: { type: String },
    buildingType: { type: String },
    occupancyState: { type: String },
    garage: { type: String },
    exterior: { type: String },
    OtherExterior: { type: String },
    weatherCondition: { type: String },
    OtherWeatherCondition: { type: String },
    soilCondition: { type: String },
    OtherSoilCondition: { type: String },
    outdoorTemperature: { type: String },
    inspectionDate: { type: Date },
    startTime: { type: String },
    endTime: { type: String },
    recentRain: { type: String },
    electricityOn: { type: String },
    OtherElectricityOn: { type: String },
    gasOilOn: { type: String },
    OtherGasOilOn: { type: String },
    waterOn: { type: String },
    OtherWaterOn: { type: String },
  },
  lotsGroundsDetails: {
    driveway: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
      comments: { type: String },
      otherComments: { type: String },
    },
    porch: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
      comments: { type: String },
      otherComments: { type: String },
    },
    stepsHandrails: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
      comments: { type: String },
      otherComments: { type: String },
    },
    deckPatio: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
      comments: { type: String },
      otherComments: { type: String },
    },
    fence: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
      comments: { type: String },
      otherComments: { type: String },
    },
    landscaping: {
      recommendations: { type: String },
      otherRecommendations: { type: String },
    },
  },
  roofDetails: {
    roofDescription: {
      style: { type: String },
      pitch: { type: String },
      visibility: { type: String },
      methodOfInspection: { type: String },
      otherMethodOfInspection: { type: String },
      ventilationPresent: { type: String },
      ventilationType: { type: String },
      otherVentilationType: { type: String },
    },
    conditionOfCoverings: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
    },
    plumbingVents: {
      material: { type: String },
      otherMaterial: { type: String },
      condition: { type: String },
      otherCondition: { type: String },
    },
  },
  exteriorDetails: {
    exterior: [
      {
        name: { type: String },
        exteriorWallType: { type: String },
        otherExteriorWallType: { type: String },
        exteriorWallCondition: { type: String },
        otherExteriorWallCondition: { type: String },
        foundationType: { type: String },
        otherFoundationType: { type: String },
        foundationCondition: { type: String },
        otherFoundationCondition: { type: String },
        foundationComments: { type: String },
        otherFoundationComments: { type: String },
        mainEntryDoor: { type: String },
        otherMainEntryDoor: { type: String },
        mainEntryDoorCondition: { type: String },
        otherMainEntryDoorCondition: { type: String },
        weatherStripping: { type: String },
        otherWeatherStripping: { type: String },
        stormDoor: { type: String },
        otherStormDoor: { type: String },
        stormDoorCondition: { type: String },
        otherStormDoorCondition: { type: String },
        doorbell: { type: String },
        otherDoorbell: { type: String },
        doorbellType: { type: String },
        otherDoorbellType: { type: String },
        sideDoor: { type: String },
        otherSideDoor: { type: String },
        sideDoorCondition: { type: String },
        otherSideDoorCondition: { type: String },
        sideDoorWeatherStripping: { type: String },
        otherSideDoorWeatherStripping: { type: String },
        patioDoor: { type: String },
        otherPatioDoor: { type: String },
        patioDoorCondition: { type: String },
        otherPatioDoorCondition: { type: String },
        patioDoorComments: { type: String },
        patioScreenDoor: { type: String },
        otherPatioScreenDoor: { type: String },
        patioScreenDoorCondition: { type: String },
        otherPatioScreenDoorCondition: { type: String },
        patioScreenDoorComments: { type: String },
        exteriorDoorsComments: { type: String },
        guttersDownspoutsRoofDrainageMaterial: { type: String },
        otherGuttersDownspoutsRoofDrainageMaterial: { type: String },
        guttersDownspoutsRoofDrainageCondition: { type: String },
        otherGuttersDownspoutsRoofDrainageCondition: { type: String },
        guttersDownspoutsRoofDrainageLeaking: { type: String },
        otherGuttersDownspoutsRoofDrainageLeaking: { type: String },
        guttersDownspoutsRoofDrainageAttachment: { type: String },
        otherGuttersDownspoutsRoofDrainageAttachment: { type: String },
        guttersDownspoutsRoofDrainageExtensionNeeded: { type: String },
        otherGuttersDownspoutsRoofDrainageExtensionNeeded: { type: String },
        guttersDownspoutsRoofDrainageComments: { type: String },
        windowsAndPatioDoorsApproximateAge: { type: String },
        otherWindowsAndPatioDoorsApproximateAge: { type: String },
        windowsAndPatioDoorsMaterialAndType: { type: String },
        otherWindowsAndPatioDoorsMaterialAndType: { type: String },
        windowsAndPatioDoorsCondition: { type: String },
        otherWindowsAndPatioDoorsCondition: { type: String },
        windowsAndPatioDoorsComments: { type: String },
        otherWindowsAndPatioDoorsComments: { type: String },
        windowScreensMaterial: { type: String },
        otherWindowScreensMaterial: { type: String },
        windowScreensCondition: { type: String },
        otherWindowScreensCondition: { type: String },
        windowScreensComments: { type: String },
        otherWindowScreensComments: { type: String },
        basementWindowsMaterial: { type: String },
        otherBasementWindowsMaterial: { type: String },
        basementWindowsComments: { type: String },
        otherBasementWindowsComments: { type: String },
        patioDoorMaterial: { type: String },
        otherPatioDoorMaterial: { type: String },
        otherPatioDoorComments: { type: String },
        patioScreenDoorMaterial: { type: String },
        otherPatioScreenDoorMaterial: { type: String },
        otherPatioScreenDoorComments: { type: String },
        gasMeterComments: { type: String },
        otherGasMeterComments: { type: String },
        electricalExteriorOutletsAndLights: { type: String },
        otherElectricalExteriorOutletsAndLights: { type: String },
        exteriorHoseBibsDescription: { type: String },
        otherExteriorHoseBibsDescription: { type: String },
        airConditioningManufacturer: { type: String },
        otherAirConditioningManufacturer: { type: String },
        airConditioningApproximateAge: { type: String },
        otherAirConditioningApproximateAge: { type: String },
        airConditioningAreaServed: { type: String },
        otherAirConditioningAreaServed: { type: String },
        airConditioningFuelType: { type: String },
        otherAirConditioningFuelType: { type: String },
        airConditioningCondition: { type: String },
        otherAirConditioningCondition: { type: String },
        airConditioningCondenserFins: { type: String },
        otherAirConditioningCondenserFins: { type: String },
        airConditioningCabinetHousing: { type: String },
        otherAirConditioningCabinetHousing: { type: String },
        airConditioningRefrigerantLineInsulation: { type: String },
        otherAirConditioningRefrigerantLineInsulation: { type: String },
        airConditioningSystemOperation: { type: String },
        otherAirConditioningSystemOperation: { type: String },
        airConditioningComments: { type: String },
        otherAirConditioningComments: { type: String },
      },
    ],
  },
  garageCarportDetails: {
    type: { type: String },
    otherType: { type: String },
    garageDoor: { type: String },
    otherGarageDoor: { type: String },
    automaticOpener: { type: String },
    otherAutomaticOpener: { type: String },
    safetyReverses: { type: String },
    otherSafetyReverses: { type: String },
    roofing: { type: String },
    otherRoofing: { type: String },
    floorFoundation: { type: String },
    otherFloorFoundation: { type: String },
    floorFoundationCondition: { type: String },
    otherFloorFoundationCondition: { type: String },
    ceiling: { type: String },
    otherCeiling: { type: String },
    ceilingCondition: { type: String },
    otherCeilingCondition: { type: String },
    exteriorWalls: { type: String },
    otherExteriorWalls: { type: String },
    interiorWalls: { type: String },
    otherInteriorWalls: { type: String },
    serviceDoor: { type: String },
    otherServiceDoor: { type: String },
    serviceDoorCondition: { type: String },
    otherServiceDoorCondition: { type: String },
    serviceDoorSelfClose: { type: String },
    otherServiceDoorSelfClose: { type: String },
    electrical: { type: String },
    otherElectrical: { type: String },
    fireSeparationWall: { type: String },
    otherFireSeparationWall: { type: String },
    comments: { type: String },
  },

  kitchenDetails : {
    kitchens: [
    {
      name: { type: String },
      countertopsCondition: { type: String },
      otherCountertopsCondition: { type: String },
      countertopsComments: { type: String },
      otherCountertopsComments: { type: String },
      cabinetsCondition: { type: String },
      otherCabinetsCondition: { type: String },
      cabinetsComments: { type: String },
      otherCabinetsComments: { type: String },
      plumbingCondition: { type: String },
      otherPlumbingCondition: { type: String },
      faucet: { type: String },
      otherFaucet: { type: String },
      functionalDrainage: { type: String },
      otherFunctionalDrainage: { type: String },
      floorMaterial: { type: String },
      otherFloorMaterial: { type: String },
      floorCondition: { type: String },
      otherFloorCondition: { type: String },
      floorComments: { type: String },
      otherFloorComments: { type: String },
      wallsCondition: { type: String },
      otherWallsCondition: { type: String },
      ceilingsCondition: { type: String },
      otherCeilingsCondition: { type: String },
      electricalCondition: { type: String },
      otherElectricalCondition: { type: String },
      rangeCondition: { type: String },
      otherRangeCondition: { type: String },
      rangeStatus: { type: String },
      otherRangeStatus: { type: String },
      dishwasherCondition: { type: String },
      otherDishwasherCondition: { type: String },
      dishwasherStatus: { type: String },
      otherDishwasherStatus: { type: String },
      rangeHoodFanCondition: { type: String },
      otherRangeHoodFanCondition: { type: String },
      rangeHoodFanStatus: { type: String },
      otherRangeHoodFanStatus: { type: String },
      refrigeratorCondition: { type: String },
      otherRefrigeratorCondition: { type: String },
      refrigeratorStatus: { type: String },
      otherRefrigeratorStatus: { type: String },
      microwaveCondition: { type: String },
      otherMicrowaveCondition: { type: String },
      microwaveStatus: { type: String },
      otherMicrowaveStatus: { type: String },
      openGroundReversePolarity: { type: String },
    },
  ],
},

  bathroomsDetails: {
    bathrooms: [
      {
        name: { type: String },
        floorMaterial: { type: String },
        floorOtherMaterial: { type: String },
        floorCondition: { type: String },
        floorOtherCondition: { type: String },
        wallsMaterial: { type: String },
        wallsOtherMaterial: { type: String },
        wallsCondition: { type: String },
        wallsOtherCondition: { type: String },
        ceilingMaterial: { type: String },
        ceilingOtherMaterial: { type: String },
        ceilingCondition: { type: String },
        ceilingOtherCondition: { type: String },
        doorMaterial: { type: String },
        doorOtherMaterial: { type: String },
        doorCondition: { type: String },
        doorOtherCondition: { type: String },
        windows: { type: String },
        otherWindows: { type: String },
        electrical: { type: String },
        otherElectrical: { type: String },
        counterCabinet: { type: String },
        otherCounterCabinet: { type: String },
        sinkBasin: { type: String },
        otherSinkBasin: { type: String },
        plumbing: { type: String },
        otherPlumbing: { type: String },
        toilet: { type: String },
        otherToilet: { type: String },
        bathtub: { type: String },
        otherBathtub: { type: String },
        standingShower: { type: String },
        otherStandingShower: { type: String },
        faucets: { type: String },
        otherFaucets: { type: String },
        waterFlow: { type: String },
        otherWaterFlow: { type: String },
        moistureStains: { type: String },
        otherMoistureStains: { type: String },
        heatSource: { type: String },
        otherHeatSource: { type: String },
        ventilation: { type: String },
        otherVentilation: { type: String },
      },
    ],
  },
  roomsDetails: {
    rooms: [
      {
        name: { type: String },
        wallsMaterial: { type: String },
        otherWallsMaterial: { type: String },
        wallsCondition: { type: String },
        otherWallsCondition: { type: String },
        ceilingMaterial: { type: String },
        otherCeilingMaterial: { type: String },
        ceilingCondition: { type: String },
        otherCeilingCondition: { type: String },
        closetType: { type: String },
        otherClosetType: { type: String },
        closetCondition: { type: String },
        otherClosetCondition: { type: String },
        floorsMaterial: { type: String },
        otherFloorsMaterial: { type: String },
        floorsCondition: { type: String },
        otherFloorsCondition: { type: String },
        doorMaterial: { type: String },
        otherDoorMaterial: { type: String },
        doorCondition: { type: String },
        otherDoorCondition: { type: String },
        windows: { type: String },
        otherWindows: { type: String },
        electrical: { type: String },
        otherElectrical: { type: String },
        heatSource: { type: String },
        otherHeatSource: { type: String },
        moistureStains: { type: String },
        otherMoistureStains: { type: String },
        comments: { type: String },
      },
    ],
  },
  ImageUploadFiles: [String],
});

const Inspection = mongoose.model('inspection', inspectionSchema);
module.exports = Inspection;